spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
#    hibernate:
#      ddl-auto: update
  application:
    name: grain-pay-api
  flyway:
    enabled: true
server:
  port: ${PORT}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
server:
  port: ${PORT}

---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    url: jdbc:postgresql://localhost:5432/grainpay_stage
    username: stage_user
    password: stage_password
server:
  port: ${PORT}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/grainpay_prod
    username: prod_user
    password: prod_password
server:
  port: ${PORT}